### PR TITLE
Added initial files

### PR DESCRIPTION
**Pull request by chase-ramsey**
Included are a public folder with css, app, vendor directories and index.html. Also included in the root are bower.json, .bowerrc, and .gitignore. App directory contains app.js.

### CODE REVIEW

**Comment by RussellRiesJr** [comment]
:+1:

**Comment by RussellRiesJr** [comment]
Still like it :+1:

**Comment by Jessicashinjo** [comment]
🍰

**Comment by CoryTohill** [comment]
👍 🌵

**Comment by Jessicashinjo** [comment]
🍰

**Pull request merged**
